name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Run test file directly
        run: |
          export PYTHONPATH=src
          python3 src/main.py  
